import turtle

# main square
blablabla = turtle.Turtle()
blablabla.speed(0)
blablabla.color("gold")
blablabla.penup()
blablabla.goto(-200,200)
blablabla.pendown()
blablabla.forward(400)
blablabla.left(-90)
blablabla.forward(400)
blablabla.left(-90)
blablabla.forward(400)
blablabla.left(-90)
blablabla.forward(400)
blablabla.left(-90)

# red square
blablabla.color("red")
blablabla.forward(100)
blablabla.left(-90)
blablabla.begin_fill()
blablabla.forward(100)
blablabla.left(-90)
blablabla.forward(100)
blablabla.left(-90)
blablabla.forward(100)
blablabla.left(-90)
blablabla.end_fill()

# blue square
blablabla.begin_fill()
blablabla.penup()
blablabla.forward(300)
blablabla.pendown()
blablabla.color("blue")
blablabla.right(90)
blablabla.forward(100)
blablabla.left(90)
blablabla.forward(100)
blablabla.left(90)
blablabla.forward(100)
blablabla.left(90)
blablabla.end_fill()

# silver square
blablabla.forward(100)
blablabla.left(-90)
blablabla.left(180)
blablabla.penup()
blablabla.forward(300)
blablabla.color("silver")
blablabla.pendown()
blablabla.begin_fill()
blablabla.forward(100)
blablabla.right(-90)
blablabla.forward(100)
blablabla.right(-90)
blablabla.forward(100)
blablabla.right(-90)
blablabla.forward(100)
blablabla.right(-90)
blablabla.end_fill()
blablabla.penup()
blablabla.left(-90)

# yellow square
blablabla.forward(200)
blablabla.pendown()
blablabla.color("yellow")
blablabla.begin_fill()
blablabla.pendown()
blablabla.forward(100)
blablabla.left(90)
blablabla.forward(100)
blablabla.left(90)
blablabla.forward(100)
blablabla.left(90)
blablabla.forward(100)
blablabla.left(90)
blablabla.forward(100)
blablabla.end_fill()
blablabla.left(90)
turtle.done()